loginSys/urls.py
from django.urls import path
from . import views



urlpatterns = [
	path('', views.accLogged, name = 'account'),
	path('cart_oauth', views.cartLogged, name = 'cart'),
	path('o_auth_order', views.myaccOrder, name = 'order'),
	path('o_auth_order_pay', views.myaccOrder_pay, name = 'pay'),
	path('o_auth_order_process', views.myaccOrder_process, name = 'process'),
	path('o_auth_order_final', views.myaccOrder_final, name = 'finish'),
	path('flash_promo', views.flashPromo, name = 'flash_sell'),
	path('free_ongkir', views.promoOngkir, name = 'free_ongkir'),
	path('game_promo', views.gamePromo, name = 'game_promo'),
	path('vc_promo', views.vcoPromo, name = 'voucher_promo'),
	path('my_voucher', views.myAccVoucher, name = 'my_voucher'),
	path('reg_sell', views.regSeller, name = 'reg_seller'),
	path('post', views.post_view, name = 'post_view'),
	path('logout', views.log_out, name = 'logout'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('search_page', views.searchPage, name = 'search'),
    path('promo_page', views.promoPage, name = 'promo'),
    path('favorite_page', views.favPage, name = 'favorit'),
    path('my_account', views.myAccountPage, name = 'account'),
    path('my_cart', views.myCart, name = 'cart'),
    path('detail', views.details, name = 'detail'),
    path('oAuth/',include(('loginSys.urls', 'loginSys'), namespace = 'oAuthLogged')),
    path('oAuthSell/', include(('sellerSide.urls', 'sellerSide'),namespace = 'home_seller')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellerSide/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name = 'home_seller'),
	path('my_product', views.product_mng, name = 'sell_product'),
	path('detail', views.product_detail, name = 'detail_product'),
	path('my_promo', views.promo_mng, name = 'sell_promo'),
	path('my_selling', views.selling_mng, name = 'sell_mng'),
	path('detail_sell', views.selling_detail, name = 'sell_detail'),
	path('my_saldo', views.saldo_mng, name = 'sell_saldo'),
]

sellerSide/controller.py
from . import models
from adminSide import models as admin_models
from loginSys import models as fk_user_main
from django.contrib.auth.models import User as user_main
from django.core.files.storage import FileSystemStorage
import os
from datetime import datetime
import requests as rq
import base64 as enc
import json

# ---------------Reguler def functions -------------------------
def get_cat_list():
	category_list = []
	Cat = admin_models.category.objects.all()
	for x in range(len(Cat)):
		category_list.append([Cat[x].name, Cat[x].id])
	return category_list

def get_promo_list(request):
	t_promo_list = []
	t_promo = models.promo.objects.filter(seller = user_main.objects.get(username = request.user))
	for x in range(len(t_promo)):
			t_promo_list.append([t_promo[x].name, t_promo[x].id])
	return t_promo_list

def get_promo_cat_list():
	cat_promo_list = []
	Cat_promo = admin_models.promo_type.objects.all()
	for x in range(len(Cat_promo)):
		cat_promo_list.append([Cat_promo[x].name, Cat_promo[x].id])
	return cat_promo_list

def upload_img (request):
	file  = request.FILES.getlist('img')
	fs = FileSystemStorage()
	# Mengatasi upload multiple file
	file_name = ''
	for x in range(len(file)):
		# System upload pada local storage
		# upload = fs.save(file[x].name, file[x])
		# name = str(fs.url(upload)).split('/')
		# file_name += name[2] + '^!@!^'
		# System upload pada server storage
		
		data = {"file":enc.b64encode(file[x].open("rb").read())}
		# print(data)
		url = "https://f-storage.000webhostapp.com/index.php?insert=true&type=png"
		response = rq.request('POST', url, data = data)
		if response.status_code == 200 or response.status_code == '200':
			jsonResponse = json.loads(json.dumps(response.json()))
			print(jsonResponse['filename']+jsonResponse['type'])
			tmpName = jsonResponse['filename']+"."+jsonResponse['type']
			file_name += tmpName + '^!@!^'
		# print(file[x].open("rb").read())
		
	return file_name

def delete_img (request, class_model = models.stuff.objects):
	file_name = request.GET.get('del')
	# get nama file di db
	if request.GET.get('id') != None :
		id_stuff = request.GET.get('id')
		# object untuk digunakan edit data
		stuff_obj = class_model.get(id = id_stuff)
		getFileName = str(stuff_obj.img_file).split('^!@!^')
		new_file_name = ''
		for x in range(len(getFileName)):
			if str(getFileName[x]) != str(file_name) and str(getFileName[x]) != '':
				new_file_name += getFileName[x]+'^!@!^'
			elif str(getFileName[x]) == str(file_name):
				url = "https://f-storage.000webhostapp.com/index.php?delete="+getFileName[x]
				response = rq.request('GET', url)
				print(response.json())
				# try:
				# 	# dir_name = 'media/'+getFileName[x]
				# 	# os.remove(dir_name)

				# except Exception as e:
				# 	print(e,'\n')
		stuff_obj.img_file = new_file_name
		stuff_obj.save()
	else:
		print('Gagal menghapus. request tidak sesuai\n')

def get_photo_profile(fk_user):
	obj = fk_user_main.user_sec.objects.get(fk_id_user = fk_user)
	return obj.Photo

# ------------ untuk kontrol produk view page  dan view detail page -------
def view_product (request, id_data = 0):
	data_product = ''
	try:
		if id_data == 0:
			data_product = models.stuff.objects.filter(seller = request.user)
		else:
			data_product = models.stuff.objects.filter(seller = request.user, id = id_data)
	except Exception as e:
		print(e,'\n')
		return [], []

	listID = []
	listView = []

	for x in range(len(data_product)):
		obj_post = models.products_post.objects.get(stuff_fk = data_product[x])
		listID.append(data_product[x].id)
		ID = data_product[x].id
		name = data_product[x].name
		desc = data_product[x].desc
		img_dir = data_product[x].img_file.split('^!@!^')
		img_field = data_product[x].img_file
		state = data_product[x].state
		stock = data_product[x].count
		price = data_product[x].price
		location = data_product[x].location
		quality = data_product[x].quality
		# untuk mendapatkan category
		category = admin_models.category.objects.get(name = data_product[x].stuff_cat).name
		# unutk dapatkan promo
		promo = models.promo.objects.filter(name = data_product[x].stuff_promo)[0].name

		tmp = [ID, name, desc, img_dir, state, stock, price, category, promo, img_field, location, range(0,quality), obj_post.ship_cost, obj_post.note]

		# tmp = [ID, name, desc, img_dir, state, stock, price, category, promo, img_field, location, range(0,quality), obj_post.ship_cost, obj_post.note]

		listView.append(tmp)

	return listView, listID

def for_modal_choice (request):
	# Mendapatkan list option dari table FK untuk addStuff
	category_list = get_cat_list()
	t_promo_list = get_promo_list(request)

	return category_list, t_promo_list

def addStuff (request):
	if request.POST.get('add_stuff') != None:
		name = request.POST['name']
		state = request.POST['state']
		price = request.POST['price']
		stock = request.POST['stock']
		desc = request.POST['desc']
		loc = request.POST['location']
		stuff_cat = admin_models.category.objects.get(id = request.POST['cat'])
		stuff_promo = models.promo.objects.get(id = request.POST['promo'])
		seller = user_main.objects.get(username = request.POST['id_seller'])
		ship_cost = request.POST.get('ship_cost')
		note = request.POST.get('note')
		# File type
		img_dir = upload_img(request)

		if len(img_dir) > 255:
			img_dir = ''

		add = models.stuff(
			name = name,
			state = state,
			price = price,
			count = stock,
			desc = desc,
			img_file = img_dir,
			quality = 0,
			location = loc,
			stuff_cat = stuff_cat,
			stuff_promo = stuff_promo,
			seller = seller
			)
		add.save() 

		add_sec = models.products_post(
			date = datetime.now().date(),
			note = note,
			ship_cost = ship_cost,
			# FK
			stuff_fk = models.stuff.objects.get(name = name,
				state = state,
				price = price,
				count = stock,
				desc = desc,
				img_file = img_dir,
				quality = 0,
				location = loc,
				stuff_cat = stuff_cat,
				stuff_promo = stuff_promo,
				seller = seller)
			)
		add_sec.save()

	else:
		print('Tidak ada request add_stuff')

def editStuff (request):
	if request.POST.get('edit_stuff') != None:
		id_stuff = request.POST['id']
		name1 = request.POST['name']
		state1 = request.POST['state']
		price1 = request.POST['price']
		stock1 = request.POST['stock']
		desc1 = request.POST['desc']
		loc1 = request.POST['location']
		stuff_cat1 = admin_models.category.objects.get(id = request.POST['cat'])
		stuff_promo1 = models.promo.objects.get(id = request.POST['promo'])
		seller1 = user_main.objects.get(username = request.POST['id_seller'])

		stuff_obj = models.stuff.objects.get(seller = user_main.objects.get(username = request.user), id = id_stuff)
		
		# id_post = request.POST.get('id_sec')
		ship_cost = request.POST.get('ship_cost')
		note = request.POST.get('note')

		post_obj = models.products_post.objects.get(stuff_fk = stuff_obj)

		if len(request.FILES.getlist('img')) != 0 :
			print('Ono gambar e broo !!!\n')
			prev_img = stuff_obj.img_file
			img_dir = upload_img(request)

			img_dir = img_dir + prev_img

			if len(img_dir) > 255:
				img_dir = prev_img

			stuff_obj.name = name1
			stuff_obj.state = state1
			stuff_obj.price = price1
			stuff_obj.count = stock1
			stuff_obj.desc = desc1
			stuff_obj.img_file = img_dir
			stuff_obj.location = loc1
			stuff_obj.stuff_cat = stuff_cat1
			stuff_obj.stuff_promo = stuff_promo1
			stuff_obj.seller = seller1

			stuff_obj.save()

			post_obj.note = note
			post_obj.ship_cost = ship_cost

			post_obj.save()

		else:
			print('Gak ono gambar e broo !!!\n')
			stuff_obj.name = name1
			print(name1,'\n')
			stuff_obj.state = state1
			stuff_obj.price = price1
			stuff_obj.count = stock1
			stuff_obj.desc = desc1
			stuff_obj.location = loc1
			stuff_obj.stuff_cat = stuff_cat1
			stuff_obj.stuff_promo = stuff_promo1
			stuff_obj.seller = seller1

			stuff_obj.save()

			post_obj.note = note
			post_obj.ship_cost = ship_cost

			post_obj.save()

	else:
		print('Tidak ada request edit\n')

def del_stuff_data(request):
	confirm = True
	if request.GET.get('del_data') != None:
		del_data = ''
		try:
			del_data = models.stuff.objects.get(id = request.GET.get('del_data'))
			# del_data_sec = models.products_post.objects.get(stuff_fk = del_data)
		except Exception as e:
			print(e,'\n')
			confirm = False

		if confirm == True:
			# img = del_data.img_file
			# img = str(img).split('^!@!^')
			# for x in range(len(img)):
			# 	if img[x] != '':
			# 		try:
			# 			os.remove('media/'+img[x])
			# 		except Exception as e:
			# 			print(e,'\n')
			# del_data_sec.delete()
			# del_data.delete()
			del_data.state = 'deactive'
			del_data.save()
		return confirm

	else:
		print('Tidak ada request HAPUS\n')
		return confirm

# ------------------ KOntrol view promo dan edit promo ------------------
def view_promos(request, id_data = 0):
	data_promos = ''
	list_view = []
	if id_data == 0:
		data_promos = models.promo.objects.filter(seller = request.user)
	else :
		data_promos = models.promo.objects.filter(seller = request.user, id = id_data)

	for x in range(len(data_promos)):
		ID = data_promos[x].id
		name = data_promos[x].name
		start_prm = str(data_promos[x].start_date)
		end_prm = str(data_promos[x].end_date)
		desc = data_promos[x].desc
		val_prm = data_promos[x].value
		prm_type = data_promos[x].promo_type
		prm_icon = ''

		if prm_type.name == 'No Promo':
			prm_icon = 'img/no_promo.png'
		elif prm_type.name == 'gratis_ongkir':
			prm_icon = 'img/ongkir-gratis.png'
		elif prm_type.name == 'voucher_discount':
			prm_icon = 'img/voucher_dc.png'
		elif prm_type.name == 'voucher_cashback':
			prm_icon = 'img/cashback.png'
		# print(prm_type.name)
		tmp = [ID, name, start_prm, end_prm, desc, val_prm, prm_type, prm_icon]
		list_view.append(tmp)

	return list_view

def add_promo(request):
	if request.POST.get('add_promo') != None:
		name = request.POST.get('name')
		st_date = request.POST.get('st')
		end = request.POST.get('end')
		desc = request.POST.get('desc')
		val = request.POST.get('val')

sellerSide/views.py
from django.shortcuts import render, redirect
from loginSys import general_fn as fn
from . import controller as ctrl
import json as simplejson
from django.contrib.auth.models import User
from loginSys import models as sec_user_models

# Create your views here.
def index (request):
	# Cek login status
	check = fn.login_check(request, state = 'seller')
	if check != None:
		return redirect(check)

	msg = ''

	obj_user = User.objects.get(username = request.user)
	obj_user_sec = sec_user_models.user_sec.objects.get(fk_id_user = obj_user)

	if request.method == "POST" and request.POST.get('edit') != None:
		msg = fn.edit_acc(request)
		if len(msg) == 0:
			return redirect('/oAuthSell')
	# print(len(msg))

	context = {

		'data':obj_user,
		'data_sec':obj_user_sec,
		'msg':msg,
		'len':len(msg),
	}

	return render(request,'seller_index.html', context)

def product_mng (request):
	# Cek login 
	check = fn.login_check(request, state = 'seller')
	if check != None:
		return redirect(check)

	view, ID = ctrl.view_product(request)
	category, promo = ctrl.for_modal_choice(request)
	access = 'yes'
	if len(category) == 0 or len(promo) == 0:
		access = 'no'

	if request.method == "POST":
		ctrl.addStuff(request)
		return redirect('/oAuthSell/my_product')

	if request.GET.get('del_data') != None:
		confirm = ctrl.del_stuff_data(request)
		if confirm == True:
			return redirect('/oAuthSell/my_product')

	context = {
		'data':view,
		'promo_choice':promo,
		'cat_choice':category,
		'access':access,
	}

	return render(request,'seller_product_mng.html', context)

def product_detail (request):
	# Cek login 
	check = fn.login_check(request, state = 'seller')
	if check != None:
		return redirect(check)

	if request.GET.get('id') == None or request.GET.get('id') == '':
		return redirect('/oAuthSell/my_product')

	view, ID = ctrl.view_product(request, id_data = request.GET.get('id'))
	category, promo = ctrl.for_modal_choice(request)

	if len(view) == 0:
		return redirect('/oAuthSell/my_product')

	access = 'yes'
	if len(category) == 0 or len(promo) == 0:
		access = 'no'

	if request.method == "POST":
		ctrl.editStuff(request)
		url = '/oAuthSell/detail?id='+str(request.GET.get('id'))
		return redirect(url)

	if request.GET.get('del') != None:
		ctrl.delete_img(request)
		url = '/oAuthSell/detail?id='+str(request.GET.get('id'))
		return redirect(url)

	context = {
		'data':view,
		'promo_choice':promo,
		'cat_choice':category,
		'access':access,
	}

	return render(request,'view_detail_product.html', context)

def promo_mng (request):
	# Cek login 
	check = fn.login_check(request, state = 'seller')
	if check != None:
		return redirect(check)

	view = ctrl.view_promos(request)
	cat_promo = ctrl.get_promo_cat_list()
	# print(view)
	access = 'yes'
	if len(cat_promo) == 0:
		access = 'no'

	if request.method == "POST" and request.POST.get('add_promo') != None:
		ctrl.add_promo(request)
		return redirect('/oAuthSell/my_promo')

	if request.method == "POST" and request.POST.get('edit_promo') != None:
		ctrl.edit_promo(request)
		return redirect('/oAuthSell/my_promo')

	if request.GET.get('del_data') != None:
		confirm = ctrl.del_promo_data(request)
		if confirm == True:
			return redirect('/oAuthSell/my_promo')

	context = {
		'data':view,
		'cat_promo':cat_promo,
		'access':access,
	}

	return render(request, 'seller_promo_mng.html',context)

def selling_mng(request):
	# Cek login
	check = fn.login_check(request, state = 'seller')
	if check != None:
		return redirect(check)

	selling, trx, finish = ctrl.selling_list(request)

	context = {
		'view':selling,
		'len_trx':len(trx),
	}

	return render(request, 'seller_sell_mng.html', context)

def selling_detail(request):
	# Cek login
	check = fn.login_check(request, state = 'seller')
	if check != None:
		return redirect(check)

	if request.GET.get('id') == None or request.GET.get('index') == None:
		return redirect('/oAuthSell/my_selling')

	if request.GET.get('id') == '' or request.GET.get('index') == '':
		return redirect('/oAuthSell/my_selling')

	view, ID = ctrl.view_product(request, id_data = request.GET.get('id'))
	sell_data = ctrl.view_selling(ID)
	sell_view = ''
	try:
		sell_view = sell_data[int(request.GET.get('index'))]
	except Exception as e:
		print(e)
		return redirect('/oAuthSell/my_selling')
	profile = []

	print(sell_view,sell_data)

	if len(sell_view) != 0:
		for x in range(len(sell_view)):
			sell_view[x].append(ctrl.get_photo_profile(sell_view[x][6]))

	context = {
		'data':view,
		'sell_view':sell_view,
		'profile':profile,
		'len_sell_data':len(sell_view)
	}

	return render(request, 'view_detail_selling.html', context)	

def saldo_mng(request):
	# Cek login
	check = fn.login_check(request, state = 'seller')
	if check != None:
		return redirect(check)

	selling, trx, finish = ctrl.selling_list(request)
	# view_all = []
	data_graph = ctrl.create_view_graph(finish)
	print(finish)

	context={
		'view':finish,
		'len_trx':len(trx),
		'graph_data':data_graph,
		}

	return render(request,'seller_saldo_mng.html',context)

sellerSide/templates/seller_saldo_mng.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>My Product | details</title>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"> </script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

</head>
<body class="body-color">
	
	<nav class="navbar navbar-dark fixed-top pb-4" style="background-color:#228B22;">
	  <div class="p-2 mt-n3 container-fluid justify-content-start"  >
	    <h5 class="text-light mb-0 h5">ZSnack Shop | </h5>
	    <h6 class="text-light mb-0"> &nbsp;Selamat datang {{user}}</h6>
	  </div>
	</nav>


	  <div class="navbar-light fixed-top"  style="background-color:#32CD32; margin-top:67px;">

			 <ul class="nav nav-tabs justify-content-center" style="border-bottom:0px;" id="myTab" role="tablist">
			 
				  <li class="mt-1 nav-item" role="presentation">
				  	<a class="btn link-dark nav-link" type="button" aria-controls="home" aria-selected="true" href="{% url 'home_seller:sell_product' %}">
				    <i class="bi bi-inboxes-fill"></i><br>My Product</a>

				  </li>
				  <li class="mt-1 nav-item" role="presentation">
				  	<a class="btn link-dark nav-link" type="button" role="tab" aria-controls="home" aria-selected="true" href="{% url 'home_seller:sell_promo' %}">
				    <i class="bi bi-gift-fill"></i><br>My Promo</a>
				  </li>
				  <li class="mt-1 nav-item" role="presentation">
				  	<a class="btn link-dark nav-link" type="button" role="tab" aria-controls="home" aria-selected="true" href="{% url 'home_seller:sell_mng' %}">
				    <i class="bi bi-graph-up"></i><br>Selling</a>
				  </li>
				   <li class="mt-1 nav-item" role="presentation">
				  	<a class="btn btn-success active" type="button" role="tab" aria-controls="home" aria-selected="true" href="{% url 'home_seller:sell_saldo' %}">
				    <i class="bi bi-wallet2"></i><br>My Saldo</a>
				  </li>
			</ul>
	  </div>

	<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color:#228B22; margin-top:135px; margin-bottom:11px">
	  <div class="container-fluid d-flex justify-content-center">
	        <input class="form-control me-2" style="width:290px" type="search" placeholder="Search" id="Search1" aria-label="Search">
	  
	  </div>
	</nav>

	<!-- Ini dibawah bagian utama -->

	<div class="container justify-content-center" style="margin-top:200px">

	  <div class="card mb-5" >
        <h5 class="card-header bg-info">Informasi</h5>
        <div class="card-body">
          <h5 class="card-title">Petunjuk Penggunaan Data Selling</h5>
          <p class="card-text">ZSnack adalah software berbasis website yang menyediakan layanan penjualan makanan daring. Tidak hanya online shop, ZSnack sendiri merupakan usaha pada bidang pangan sendiri yang juga memfasilitasi pengusaha lain untuk memasarkan produknya. Halaman ini adalah halaman depan dari user siswa atau peserta tes. Di bawah ini menu menu yang disediakan untk peserta tes..</p>
        </div>
      </div>

      <h3 class="mb-3 mt-3">Grafik Pendapatan Tahun Ini</h3>
      <div id="saldo"></div>

    <div id="cards">
		{% if len_trx != 0 %}
		
			{% for v in view %}

			{% if v.1|length != 0 %}
			
				<div class="card mt-3" style="width: 100%;">
				 	<div class="alert alert-success">
					  <strong>Transaksi yang sudah tuntas !</strong><br>
					  <strong>Kode transaksi : {{ v.0 }}</strong>
					</div>
				  <div class="card-body">
				  	<strong>Nama pembeli : </strong> {{ v.2.buyer }}<br>
						<strong>Tanggal transaksi : </strong> {{ v.2.date }}<br>
						<strong>Harga produk : {{ v.2.pay_value }} Rupiah</strong><br>
						<strong>Biaya ongkir : {{ v.2.ship_cost }} Rupiah</strong>
				  </div>
				</div>

			{% endif %}			

			{% endfor %}

		{% else %}
			<div class="container justify-content-center text-center" style="margin-top:200px;">
				<i class="bi bi-cart-fill text-secondary opacity-25" style="font-size:200pt;"></i>
				<br>
				<h5 class="text-dark mb-5">Belum ada data belanja di pesan.</h5>
				
				<h6 class="text-dark mb-3"> Selamat berbelanja :) !!!.</h6>
			</div>
		{% endif %}
		</div>
	</div>

	
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script type="text/javascript">
		var optionsSaldoCharts = {
		  	chart: {
		    	type: 'line'
		  	},
		  	series: [{
				name: 'Saldo per tahun',
				// Data list harus 12, Jika sudah 12 harus di reset ke tahun ke depannya
				data: {{ graph_data|safe }},
			}],
			xaxis: {
				categories: ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']
			}
		}

		var saldoChart = new ApexCharts(document.querySelector("#saldo"), optionsSaldoCharts);

		saldoChart.render();
	</script>
	<script src="{% static 'script/live_search_main.js' %}"></script>
	<script type="text/javascript">
		document.getElementById('Search1').addEventListener('keyup', function(){
			search('Search1', 'cards');
		});
	</script>

</body>
</html>