loginSys/urls.py
from django.urls import path
from . import views



urlpatterns = [
	path('', views.accLogged, name = 'account'),
	path('cart_oauth', views.cartLogged, name = 'cart'),
	path('o_auth_order', views.myaccOrder, name = 'order'),
	path('o_auth_order_pay', views.myaccOrder_pay, name = 'pay'),
	path('o_auth_order_process', views.myaccOrder_process, name = 'process'),
	path('o_auth_order_final', views.myaccOrder_final, name = 'finish'),
	path('flash_promo', views.flashPromo, name = 'flash_sell'),
	path('free_ongkir', views.promoOngkir, name = 'free_ongkir'),
	path('game_promo', views.gamePromo, name = 'game_promo'),
	path('vc_promo', views.vcoPromo, name = 'voucher_promo'),
	path('my_voucher', views.myAccVoucher, name = 'my_voucher'),
	path('reg_sell', views.regSeller, name = 'reg_seller'),
	path('post', views.post_view, name = 'post_view'),
	path('logout', views.log_out, name = 'logout'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('search_page', views.searchPage, name = 'search'),
    path('promo_page', views.promoPage, name = 'promo'),
    path('favorite_page', views.favPage, name = 'favorit'),
    path('my_account', views.myAccountPage, name = 'account'),
    path('my_cart', views.myCart, name = 'cart'),
    path('detail', views.details, name = 'detail'),
    path('oAuth/',include(('loginSys.urls', 'loginSys'), namespace = 'oAuthLogged')),
    path('oAuthSell/', include(('sellerSide.urls', 'sellerSide'),namespace = 'home_seller')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginSys/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class user_sec (models.Model):
	fk_id_user = models.ForeignKey(User, on_delete=models.CASCADE)
	status = models.CharField(max_length = 10)
	Photo = models.CharField(max_length = 50, blank=True)
	address = models.TextField(blank=True)
	phone = models.CharField(max_length = 20, blank=True)

	def __str__(self):
		return str(self.fk_id_user)

class trx_data (models.Model):
	date = models.DateField()
	trx_code = models.CharField(max_length = 20)
	buyer = models.ForeignKey(User, on_delete=models.CASCADE)
	ship_cost = models.IntegerField()
	stuff_cost = models.IntegerField()
	total_price = models.IntegerField()

	def __str__(self):
		return str(self.date)

loginSys/controller.py
from sellerSide import models as sell_models
from django.shortcuts import render, redirect
from . import models as sec_user_models
import string
import random
from datetime import datetime
from django.db.models import Q
from midtransclient import Snap, CoreApi
import json
import requests as rq

SERVER_KEY = 'Mid-server-i1A9vgpsxiWD71rhc_M3EZya'
CLIENT_KEY = 'Mid-client-J6Nn40pIMpSE7apJ'


def view_cart(request, state = 'cart'):
	obj_carts = sell_models.cart.objects.filter(buyer = request.user, state_order = state)
	all_prd = []
	for x in range(len(obj_carts)):
		all_prd.append(obj_carts[x].stuff)

	items = {i:all_prd.count(i) for i in all_prd}
	keys_item = list(items.keys())
	value_item = list(items.values())

	arr_view = []
	for x in range(len(keys_item)):
		obj_post = sell_models.products_post.objects.get(stuff_fk = keys_item[x])
		img_file = keys_item[x].img_file.split(('^!@!^'))
		arr_view.append([keys_item[x], obj_post, img_file ,value_item[x]])
	# print(arr_view)
	return arr_view

# def get_user(request):
# 	obj_user_sec = sec_user_models.user_sec.objects.get(fk_id_user = request.user)

# Hanya untuk menset tampilan datanya tanpa disave
def set_for_pay(request, stuff_data):
	obj_user_sec = sec_user_models.user_sec.objects.get(fk_id_user = request.user)
	address = obj_user_sec.address
	phone_num = obj_user_sec.phone
	price_stufs = 0
	price_ship = 0
	total = 0
	# data passing array
	for x in range(len(stuff_data)):
		pointer = False
		price_stufs += (stuff_data[x][0].price * stuff_data[x][3])
		if x == 0:
			if stuff_data[x][0].stuff_promo.promo_type.name == 'gratis_ongkir':
				price_ship += stuff_data[x][1].ship_cost*(stuff_data[x][0].stuff_promo.value/100)
			else:
				price_ship += stuff_data[x][1].ship_cost
		else:
			for y in range(len(stuff_data)):
				if y != x:
					if stuff_data[x][0].seller == stuff_data[y][0].seller:
						pointer = True
			if pointer == False:
				if stuff_data[x][0].stuff_promo.promo_type.name == 'gratis_ongkir':
					price_ship += stuff_data[x][1].ship_cost*(stuff_data[x][0].stuff_promo.value/100)
				else:
					price_ship += stuff_data[x][1].ship_cost

	total = price_stufs+price_ship
	obj_cart = sell_models.cart.objects.filter(buyer = request.user, state_order = 'order')

	return [address, price_stufs, price_ship, total, obj_cart, phone_num]

def action_control(request):
	# Proses 1 => Ubah data cart menjadi ordered
	# Proses 2 => Edit data alamat pembeli
	# Proses 2 => simpan Total bayar / trx ke models trx (buat lagi)
	# Proses 3 => simpan semua cart dan ID trx yang ordered ke selling models
	ids_prd = request.POST.getlist('id_stuffs')
	ids_post = request.POST.getlist('post_stuffs')
	address_buyer = request.POST.get('address')
	phone_buyer = request.POST.get('phone')
	obj_carts = []
	N = 15
  
	# using random.choices()
	# generating random strings 
	# print(ids_prd)
	obj_prd = []
	for x in range(len(ids_prd)):
		obj_prd.append(sell_models.stuff.objects.get(id = int(ids_prd[x])))
	trx_ID = ''.join(random.choices(string.ascii_uppercase + string.digits, k = N))
	for x in range(len(obj_prd)):
		obj_carts += sell_models.cart.objects.filter(buyer = request.user, stuff = obj_prd[x], state_order = 'order')

	if request.method == "POST" and request.POST.get('buy') != None:
		# print(obj_carts)
		ship_cost = request.POST.get('price_ship')
		stuff_cost = request.POST.get('price_stuff')
		total = request.POST.get('total')
		print(ship_cost, stuff_cost, total)
		# ubha semua cart menjadi ordered
		for x in range(len(obj_carts)):
			obj_carts[x].state_order = 'ordered'
			obj_carts[x].save()
		# edit data alamat
		obj_user_sec = sec_user_models.user_sec.objects.get(fk_id_user = request.user)
		obj_user_sec.address = address_buyer
		obj_user_sec.phone = phone_buyer
		obj_user_sec.save()
		# Menyimpan data ke selling models
		for x in range(len(obj_carts)):
			add_sell = sell_models.selling(
				date = datetime.now().date(),
				pay_value = 0,
				count = 1,
				# ship cost kosonngkan untuk sementara
				ship_cost = 0,
				pay_method = 'transfer',
				trx_id = trx_ID,
				cart_ordered = obj_carts[x],
				buyer = request.user
				)
			add_sell.save()
		# Menyimpan data de models trx beserta data pembelian
		add_trx = sec_user_models.trx_data(
			date = datetime.now().date(),
			trx_code = trx_ID,
			buyer = request.user,
			ship_cost = int(float(ship_cost)),
			stuff_cost = int(float(stuff_cost)),
			total_price = int(float(total))
			)
		add_trx.save()

	if request.method == "POST" and request.POST.get('cancel') != None:
		for x in range(len(obj_carts)):
			obj_carts[x].state_order = 'cart'
			obj_carts[x].save()

def set_process_status(trx_code, pay_status, pay_total):
	if pay_status != '':
		if pay_status == 200 or pay_status == '200':
			print('Pembayaran sukses')
			# Dapatkan selling dengan trx id
			sells = sell_models.selling.objects.filter(trx_id = trx_code)
			for x in range(len(sells)):
				cart = sells[x].cart_ordered
				# Mrngubah status
				cart.state_order = 'process'
				cart.state_buy = 'buyed'
				cart.save()
				sells[x].pay_value = pay_total
				sells[x].save()

			add = sell_models.profit(
				date = datetime.now().date(),
				profit_sell = pay_total,

				# Fk
				sell_code = sells[0]
				)
			add.save()
		elif pay_status == 201 or pay_status == '201':
			print('Pembayaran pending')
			# Dapatkan selling dengan trx id
			sells = sell_models.selling.objects.filter(trx_id = trx_code)
			for x in range(len(sells)):
				cart = sells[x].cart_ordered
				# Mrngubah status
				cart.state_order = 'ordered'
				cart.state_buy = 'pending'
				cart.save()
				sells[x].pay_value = 0
				sells[x].save()

			add = sell_models.profit(
				date = datetime.now().date(),
				profit_sell = 0,

				# Fk
				sell_code = sells[0]
				)
			add.save()
		return redirect('/oAuth/o_auth_order_pay')

def view_unpay (request):
	obj_selling = sell_models.selling.objects.filter(buyer = request.user, pay_value = 0)
	
	all_trx = []
	for x in range(len(obj_selling)):
		all_trx.append(obj_selling[x].trx_id)

	items = {i:all_trx.count(i) for i in all_trx}
	trx_code = list(items.keys())
	count_trx = list(items.values())

	carts = []
	stuffs = []
	transaction_token = []
	for x in range(len(trx_code)):
		carts.append(sell_models.selling.objects.filter(trx_id = trx_code[x], buyer = request.user))
		tmp = []
		for y in range(len(carts[x])):
			tmp.append(carts[x][y].cart_ordered.stuff.id)
		prd_ids = {i:tmp.count(i) for i in tmp}
		ids = list(prd_ids.keys())
		count_ids = list(prd_ids.values())
		tmp = []
		print(ids)
		for y in range(len(ids)):
			# print(ids[0])
			try:
				obj_prd = sell_models.stuff.objects.get(id = ids[y], state = 'active')
				obj_post = sell_models.products_post.objects.get(stuff_fk = obj_prd)
				tmp.append([obj_prd, obj_post, obj_prd.img_file.split('^!@!^')[0], count_ids[y]])
			except Exception as e:
				print(e)
		# Note : 1 tmp berisi banyak barang dalam 1 trx

		# Membuat checkout
		snap = Snap(
			is_production = True,
			server_key = SERVER_KEY,
			client_key = CLIENT_KEY,
			)

		# stuff_order = ctrl.view_cart(request, state = 'ordered')
		# print(stuff_order)
		# stuffs, trx = ctrl.view_unpay(request)
		# Buat checkout secara array
		# for x in range(trx):
		# id_trx = trx_code[x]
		amount = sec_user_models.trx_data.objects.get(trx_code = trx_code[x]).total_price
		snp = []
		pay_status = ''
		va_num = ''
		try:
			# token = snap.create_transaction_token({
			# 		"transaction_details":{
			# 			"order_id":trx_code[x],
			# 			"gross_amount":amount
			# 		}, "credit_card":{
			# 			"secure":True
			# 		}
			# 	})
			token = snap.create_transaction_token({
					"transaction_details":{
						"order_id":trx_code[x],
						"gross_amount":amount
					}, "credit_card":{
						"secure":True
					}
				})
			snp = token
			transaction_token.append(token)
		except Exception as e:
			# Mencari status dari checkout yang sudah pernaj dibuat
			url = 'https://api.midtrans.com/v2/'+trx_code[x]+'/status'

			payload = "\n\n"
			headers = {
			  'Accept': 'application/json',
			  'Content-Type': 'application/json',
			  'Authorization': 'Basic TWlkLXNlcnZlci1pMUE5dmdwc3hpV0Q3MXJoY19NM0VaeWE6'
			}

			response = rq.request("GET", url, headers=headers, data = payload)
			if response.status_code == 200 or response.status_code == '200':
				pay_status = json.loads(json.dumps(response.json()))['status_code']
				va_num = json.loads(json.dumps(response.json()))['va_numbers'][0]

			print(response.status_code)
			# print('\n',response.text.encode('utf8'),'\n')
			print(e)

		if pay_status != '':
			set_process_status(trx_code[x], pay_status, amount)

		stuffs.append([trx_code[x],tmp, snp, snap.api_config.client_key, pay_status, va_num])
		

	print(stuffs, trx_code)
	return stuffs, trx_code

def view_finish (request):
	obj_selling = sell_models.selling.objects.filter(Q(buyer = request.user) & ~Q(pay_value = 0))
	
	all_trx = []
	for x in range(len(obj_selling)):
		all_trx.append(obj_selling[x].trx_id)

	items = {i:all_trx.count(i) for i in all_trx}
	trx_code = list(items.keys())
	count_trx = list(items.values())

	sells = []
	stuffs = []
	stuffs_f = []
	stuffs_p = []
	for x in range(len(trx_code)):
		# state_order.append(sell_models.selling.objects.filter(trx_id = trx_code[x])[0].cart_ordered.state_order)
		sells.append(sell_models.selling.objects.filter(trx_id = trx_code[x], buyer = request.user))
		tmp = []
		for y in range(len(sells[x])):
			tmp.append(sells[x][y].cart_ordered.stuff.id)
			# state_order.append(sells[x][y].cart_ordered.state_order)
		prd_ids = {i:tmp.count(i) for i in tmp}
		ids = list(prd_ids.keys())
		count_ids = list(prd_ids.values())

		# Looping menentukan status order
		states_order = []
		for y in range(len(ids)):
			state_order = ''
			for z in range(len(sells[x])):
				if str(ids[y]) == str(sells[x][z].cart_ordered.stuff.id):
					state_order =  sells[x][z].cart_ordered.state_order
			# print(state_order, trx_code[x])
			states_order.append(state_order)

		tmp = []

loginSys/templates/my_acc_logged.html
{% extends "base_my_acc_page.html" %}
{% load static %}

{% block content %}

<div class="container justify-content-center" style="margin-top:200px">

	<ul class="nav nav-tabs">
	  <li class="nav-item tab-acc-link-menu">
	    <a class="nav-link active text-success" style="border-bottom-color:#04a63c; background-color:#f8f9fa;" aria-current="page" href="#">Beli</a>
	  </li>
	  <li class="nav-item tab-acc-link-menu">
	    <a class="nav-link text-dark" href="{% url 'oAuthLogged:post_view' %}">Postingan</a>
	  </li>
	</ul>

	<div class="navbar navbar-light bg-white mt-3 p-2 rounded-top">
	  <div class="container-fluid">
	    <a class="navbar-brand">
	    	<i class="bi bi-clipboard-check fs-3 align-middle me-2 text-primary"></i> Pesanan Saya
	    </a>
	    <div class="d-flex">
	      <a class="navbar-brand me-2" href="{% url 'oAuthLogged:order' %}"> 
	      	<i class="bi bi-chevron-right fs-4 align-middle"></i>
	      </a>
	    </div>
	  </div>
	</div>

	<div class="cat-box-2 rounded-bottom p-2">
		<div>
				<div class="d-flex align-items-start">
					<ul class="list-group d-flex align-items-start cat-list justify-content-center">
						<li class="list-group-item  list-vertic-cat text-center">
							<div class="list-group">
								<a class="list-group-item" href="{% url 'oAuthLogged:pay' %}">
									<i class="bi bi-credit-card-2-back fs-0"></i><br> Belum Bayar
								</a>
							</div>
						</li>
						<li class="list-group-item  list-vertic-cat text-center">
							<div class="list-group">
								<a class="list-group-item" href="{% url 'oAuthLogged:process' %}">
									<i class="bi bi-box-seam fs-0"></i><br> Diproses
								</a>
							</div>
						</li>
						<li class="list-group-item  list-vertic-cat text-center">
							<div class="list-group">
								<a class="list-group-item" href="{% url 'oAuthLogged:finish' %}">
									<i class="bi bi-star fs-0"></i><br> Beri Penilaian
								</a>
							</div>
						</li>
					</ul>
				</div>
			</div>
	</div>

	<div class="navbar navbar-light mt-3 p-2 rounded-5" style="background-color:aquamarine;">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'oAuthLogged:reg_seller' %}">
	    	<i class="bi bi-shop-window fs-3 align-middle me-2 text-danger"></i> Mulai Jual
	    </a>
	    <div class="d-flex">
	      <a class="navbar-brand me-2" href="{% url 'oAuthLogged:reg_seller' %}"> 
	      	Register Gratis <i class="bi bi-chevron-right fs-4 align-middle"></i>
	      </a>
	    </div>
	  </div>
	</div>

	<div class="navbar navbar-light mt-3 p-2 rounded-5 mb-5" style="background-color:antiquewhite;">
	  <div class="container-fluid" >
	    <a class="navbar-brand" data-bs-toggle="modal" data-bs-target="#editAkunModal" href="#">
	    	<i class="bi bi-person fs-3 align-middle me-2 text-danger"></i> Atur Akun
	    </a>
	    <div class="d-flex">
	      <a class="navbar-brand me-2" data-bs-toggle="modal" data-bs-target="#editAkunModal" href="#"> 
	      	Atur Ulang Akun <i class="bi bi-chevron-right fs-4 align-middle"></i>
	      </a>
	    </div>
	  </div>
	</div>


	<div class=" mt-3 p-2 rounded-5 text-center" >
	  <a class="btn btn-danger btn-lg btn-block" href="{% url 'oAuthLogged:logout' %}">Logout</a>
	</div>

	<div>
        {% if len != 0 %}
        <div class="mt-5 card">
          <h5 class="card-header bg-danger text-light">Pesan Kesalahan</h5>
          <div class="card-body">
            {% for err in msg %}
               <p class="card-text">{{ err }}</p>
            {% endfor %}
          </div>
        </div>
        {% endif %}
      </div>

	<!-- Modal Edit Akun -->
	<div class="modal fade" id="editAkunModal" tabindex="-1" aria-labelledby="Edit Akun Modal" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">Edit Akun</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      
	      <form method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="modal-body">
          <div class="mb-3 justify-content-center">
            <img class="rounded-circle" style="margin-left:23%" src="https://f-storage.000webhostapp.com/media/{{ data_sec.Photo }}" width="50%" height="50%">
          </div>
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="username" value="{{ data.username }}">
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Alamat E-Mail</label>
            <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" value="{{ data.email }}">
            <div id="emailHelp" class="form-text">Kerahasian data anda kami jamin</div>
          </div>
          <div class="mb-3">
            <label for="fname" class="form-label">Nama depan</label>
            <input type="text" name="fname" class="form-control" id="fname" value="{{ data.first_name }}">
          </div>
          <div class="mb-3">
            <label for="lname" class="form-label">Nama belakang</label>
            <input type="text" name="lname" class="form-control" id="lname" value="{{ data.last_name }}">
          </div>
          <div class="mb-3">
            <label for="pwd" class="form-label">Password Lama</label>
            <input type="password" name="pwd" minlength="10"  class="form-control" id="pwd">
          </div>
          <div class="mb-3">
            <label for="pwd2" class="form-label">Password Baru</label>
            <input type="password" name="pwd2" minlength="10"  class="form-control" id="pwd2">
          </div>
          <div class="mb-3">
            <label for="img" class="form-label">Foto Profil</label>
            <input type="file" name="img" accept="img/*" class="form-control" id="img">
          </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" name="edit" class="btn btn-primary">Simpan</button>
          </div>
        </form>
	    </div>
	  </div>
	</div>


</div>
	
{% endblock content %}

loginSys/templates/my_cart_logged.html
{% extends "base_my_cart.html" %}

{% block content %}
	
	<div class="container" style="margin-top:200px;">

		{% if len_view != 0 %}

			<form method="post">
				{% csrf_token %}
			{% for v in view %}

				{% if v.0.state == 'active' %}
				
				<div class="card mb-3 mt-2" style="width: 100%;">
				  <div class="row g-0" style="flex-wrap:unset;">
				    <div class="col-md-4" style="width:250px;">
				      <a href="/detail?prd={{ v.0.id }}&post={{ v.1.id }}">
				      	<img src="https://f-storage.000webhostapp.com/media/{{ v.2.0 }}" class="img-fluid rounded-start" alt="...">
				      </a>
				    </div>
				    <div class="col-md-8" style="width:40%">
				      <div class="card-body">
				        <h5 class="card-title">
				        	<input type="checkbox" name="check" value="{{ v.0.id }}">
					        {{ v.0.name }}
					    </h5>
				        <div class="card-text">Rp.{{ v.0.price }},00</div>
				        <div class="card-text">Jumlah : {{ v.3 }} produk</div>
				        <a type="submit" name="cart" class="btn btn-primary mt-5" href="?add_cart={{ v.0.id }}">+</a>
				        <a type="submit" name="cart" class="btn btn-danger mt-5" href="?min_cart={{ v.0.id }}">-</a>
				      </div>
				    </div>
				  </div>
				</div>

				{% endif %}
				
			{% endfor %}
			<button type="submit" name="buy" class="btn btn-danger">Beli Sekarang</button>
			</form>

		{% else %}

			<div class="container justify-content-center text-center" style="margin-top:200px;">
				<i class="bi bi-cart-fill text-secondary opacity-25" style="font-size:200pt;"></i>
				<br>
				<h5 class="text-dark mb-5">Belum ada data belanja di keranjang.</h5>
				
				<h6 class="text-dark mb-3"> Selamat berbelanja :) !!!.</h6>
			</div>

		{% endif %}

	</div>

{% endblock content %}